Repository espressif/idf-eclipse-plugin, pull requests merged in 2023-01, with the labels that each got.

#678 IEP-853: The default debug config command doesn't match the selected target
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java
Labels: bug, Debugging

#676 IEP-831: Set remotetimeout to 20 sec for GDB Client
  bundles/com.espressif.idf.debug.gdbjtag.openocd/plugin.xml
  bundles/com.espressif.idf.debug.gdbjtag.openocd/preferences.ini
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/OpenOCDPluginStartup.java
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/preferences/DefaultPreferenceInitializer.java
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/preferences/DefaultPreferences.java
Labels: enhancement, Debugging, configuration

#685 IEP-862 Repeatedly ask to install some missing tools
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java
Labels: bug

#686 IEP-864 Clean commands do not work with custom build directories
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/ProjectCleanCommandHandler.java
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/ProjectFullCleanCommandHandler.java
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/PythonCleanCommandHandler.java
Labels: bug
