Repository espressif/idf-eclipse-plugin, pull requests merged in 2023-11, with the labels that each got.

#799 IEP-1000 Board doesn't match the target after cancel in debug/jtag tab
  bundles/com.espressif.idf.debug.gdbjtag.openocd/plugin.properties
  bundles/com.espressif.idf.debug.gdbjtag.openocd/plugin.xml
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/SvdPathResolver.java
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/Messages.java
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabSvdTarget.java
  bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/messages.properties
  bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
  bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/Messages.java
  bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/messages.properties
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/LaunchBarListener.java
Labels: bug

#835 IEP-1041: Parse Compile Commands File exception when using multiple esp-idf versions
  bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
Labels: bug

#847 fix: IEP Update site naming convention
  features/com.espressif.idf.feature/feature.xml
  releng/com.espressif.idf.update/category.xml
Labels: UX

#818 Update application tracing part of README.md
  README.md
Labels: documentation, needs translation:CN

#826 IEP-1033 esptool write_flash command in the IDE
  README.md
  bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFConstants.java
  bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/EspToolCommands.java
  bundles/com.espressif.idf.ui/OSGI-INF/l10n/bundle.properties
  bundles/com.espressif.idf.ui/icons/Write_Binary_Data_to_Flash.png
  bundles/com.espressif.idf.ui/plugin.xml
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/Messages.java
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/WriteFlashDialog.java
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/messages.properties
  bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/WriteFlashCommandHandler.java
Labels: enhancement
